### ISSUE TITLE
Error in Chrome 75.0.3770.100: Uncaught Instance of 'minified:p'

### ISSUE THREAD

**Issue by step4** [dart-lang/stagehand#620]
steps to reproduce after fresh install of windows 10
```
choco install dart-sdk
pub global activate webdev
pub global activate stagehand
mkdir angular_dart_web
cd angular_dart_web
stagehand web-angular
pub get
webdev serve
```

open `http://127.0.0.1:8080/` in Chrome:
```error
Uncaught Instance of 'minified:p'
    at Object.b (http://127.0.0.1:8080/webdev/src/serve/injected/client.js:367:3)
    at nq.$0 (http://127.0.0.1:8080/webdev/src/serve/injected/client.js:5445:20)
    at Object.uK (http://127.0.0.1:8080/webdev/src/serve/injected/client.js:1268:5)
    at kK.uP (http://127.0.0.1:8080/webdev/src/serve/injected/client.js:1270:7)
    at lL.$1 (http://127.0.0.1:8080/webdev/src/serve/injected/client.js:4865:3)
    at vk (http://127.0.0.1:8080/webdev/src/serve/injected/client.js:441:17)
    at MutationObserver.<anonymous> (http://127.0.0.1:8080/webdev/src/serve/injected/client.js:449:51)
```

**Comment by kwalrath** [comment]
@johnpryan or @domesticmouse or @vsmenon, does this sound familiar?

**Comment by vsmenon** [comment]
@jakemac53 @grouma

**Comment by step4** [comment]
Okay it's weird the error doesn't appear after reinstalling dart-sdk
But now after executing `webdev serve` the page is loading but hangs here:
![Unbenannt](https://user-images.githubusercontent.com/11348121/61292984-f1033200-a7d2-11e9-814b-63d5c0d08b8c.PNG)

**Comment by step4** [comment]
Found the problem.
webdev indicates that it is serving on `http://127.0.0.1:8080`
after using `http://localhost:8080` everything works

**Comment by grouma** [comment]
That's weird. I can't reproduce this issue but we will now serve the client unminified which will hopefully give a better error.
